title = "Kyle's Blog"
baseURL = "https://2019052596.nnm.jnu.rocks/hugo/"
theme = "bilberry-hugo-theme"

# Generate the robots.txt file for SEO
enableRobotsTXT = true
# Change to one of your content languages definded at the end.
DefaultContentLanguage = "中"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = ""

# Enable / Disable open link with a new tab.
[blackfriday]
  hrefTargetBlank = false

[params]
  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Kyle"
  description = "Kyle's Blog"
  keywords = "blog,personal,responsive,search,font awesome,pages,posts,multilingual,highlight.js,syntax highlighting,premium,shortcuts"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "8PHCMX0K5Z"
  algolia_apiKey    = "cbd03d73701a69e7ae8d7d4cbfc5cbba"
  algolia_indexName = "hugo_index"
    # Set this option to false if you want to search within all articles in all languages at once
    algolia_currentLanguageOnly = true

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Powered by Hugo"

    # if you want to use gravatar for the header image
    gravatarEMail = "962972837@qq.com"

    # set an path to the image file you want to use | overwrites gravatar
    customImage = ""

    # define the icon you want to use for the overlay for the customImage or gravatar.
    overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = true

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    # pinnedPost = "/content/github/"
    # Set to true to pin only to the first page, false to all pages
    # pinOnlyToFirstPage = true

    # enable automatical localization of the article's PublishedDate with momentjs
    enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = false

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 7

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 7

    # show a language chooser in the footer
    showFooterLanguageChooser = true

    # social media profile urls for the footer links
    showSocialMedia = true

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
      { link = "https://github.com/kylechoy", icon = "fab fa-github" },
      { link = "http://wpa.qq.com/msgrd?v=3&uin=962972837&site=qq&menu=yes", icon = "fab fa-qq" },
      { link = "https://weibo.com/5017897265", icon = "fab fa-weibo" },
    ]

    # credits line configuration
    copyrightBy = "by Kyle"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2020"
    copyrightUrl = "https://github.com/kylechoy"
    creditsText = "Bilberry Hugo Theme"
    creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"


## 配置valine评论
[params.valine]
    enable = true
    appId = 'gUtwUB2rxA9S1cuA7n3nTcCz-gzGzoHsz'
    appKey = 'ql6UYDI0zhNjwElhtBfcv0vh'
    avatar = 'mm' 
    placeholder = '说点什么吧...'
    visitor = true


# customize your available languages for your multi-langual site
# or delete the [Languages] blog to use the theme with only one supported language
[Languages]
  [Languages."中"]
    weight = 1
  [Languages.en]
    weight = 2
# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"
[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]
  
  